### ISSUE TITLE
panic: invalid stat name 'system.aes-aes_datapath.tlb.hits'

### ISSUE THREAD

**Issue by majid169** [harvard-acc/gem5-aladdin#3]
I can create the config files (aladdin/gem5-cache/gem5-cpu)and compile the simulator. However, when I run the run.sh file I have 2 problems. First, I need to change the cpu-type from timing to DerivedO3 and memory type from DDR3_1600 to something else because they are not longer supported. Then, if I run the simulator I get this error:
panic: invalid stat name 'system.aes-aes_datapath.tlb.hits'
And then simulation is terminated.
Any idea?
Thanks

**Comment by xyzsam** [comment]
This is because your gem5.cfg file contains a section called "aes-aes". That section name will get turned into the datapath name, which in turn gets embedded into your stat name, and stats cannot have dashes in their names, only underscores.

I'll have this fixed in the future, where dashes just get turned directly into underscores for naming purposes.

**Comment by xyzsam** [comment]
Closing due to lack of discussion.
